Serilog:
    Using: [ "Serilog.Sinks.Console" ]
    MinimumLevel:
        Default: Verbose #Information
        Override:
            SS14: Verbose

DetailedErrors: true
ConnectionStrings:
    default: "Server=127.0.0.1;Port=5432;Database=maps;User Id=postgres;Password=postgres;"

Auth:
    ApiKey: "debug"

Processing:
    TargetDirectory: "/tmp/mapstest/build"
    DirectoryPoolMaxSize: 3

Github:
    AppName: "SS14.MapServer"
    TemplateLocation: "Resources/Templates"

Server:
    CorsOrigins:
        - "http://localhost:5173"
    Language: "en-US"

Git:
    Branch: "mapservertest"
